version: v1.0
name: Deploy to production
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
blocks:
  - name: Transfer
    task:
      secrets:
        - name: ssh-key
      jobs:
        - name: transfer
          commands:
            - echo 'Transferring app to production...'
            - chmod 0600 ~/ssh-key/id_rsa*
            - scp -i ~/ssh-key/id_rsa -o StrictHostKeyChecking=no dist/* {run,stop}.sh Dockerfile .dockerignore docker-compose.yml ubuntu@109.237.25.250:~/apps/catena/web/

  - name: Deploy
    task:
      secrets:
        - name: ssh-key
      jobs:
        - name: deploy
          commands:
            - echo 'Deploying app on server...'
            - chmod 0600 ~/ssh-key/id_rsa*
            - cp ~/id_rsa.pub ~/.ssh
            - ssh -i ~/ssh-key/id_rsa -o StrictHostKeyChecking=no ubuntu@109.237.25.250 'cd ~/apps/catena/web;docker build -t catena_web .;./run.sh'
